### PR TITLE
Add style

### PR DESCRIPTION
**Pull request by safar1212**
In this pull request, 
I styled the project.

### CODE REVIEW

**Review by vechicin — APPROVED** [review]
# Hi @safar1212 ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights ⚡ 

- [x] Nice styling!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by vechicin** [comment]
https://github.com/safar1212/Leaderboard-app/blob/4c94b61b86f6896499fb86b6c5685e5d4b26e522/README.md?plain=1#L27-L44

I recommend you remove all of these instructions and simply tell users to run the `npm install` command as it will install all of the necessary dependencies for the project to run properly. Since this project is built with Webpack, please add instructions on the command that needs to be run to start the live server.

Screen Shot 2022-06-17 at 7 42 14

**Review by KDlamini — APPROVED** [review]
### Hi @safar1212 🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the required changes. 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!🎊 🥳 

# Status: Approved ✔️ 
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by safar1212** [comment]
@KDlamini Do I need to merge it only to the development branch? Or do I need to do it to the main branch too?

**Pull request merged**
